### PR TITLE
doc: first draft of documentation on ci.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by iocanel** [comment]
@zregvart @rhuss: For now I don't intend to add anything else, please let me know if you need me to focus emphasize on anything.

**Comment by zregvart** [comment]
The Nexus chapter is outdated with #4, but I would merge this in to have more visibility, then we can update it with details as needed.

**Comment by iocanel** [comment]
Thanks for the feedback @zregvart and for taking the time to read it. I updated the nexus section.

**Review by zregvart — APPROVED** [review]
👍

**Comment by rhuss** [comment]
@iocanel thanks a lot for your efforts to write this down ! It is next on my reading list, but just about to get TP1 one.

**Pull request merged**
